---
MatA:
  num_rows: 56
  num_cols: 9 
  addressing: "strided"
  bbox: [0, 0, 55, 8]
  trans:  no

MatB:
  num_rows: 9
  num_cols: 9
  addressing: "strided"
  bbox: [0, 0, 8, 8]
  trans:  no

MatC:
  num_rows: 56
  num_cols: 9
  addressing: "strided"
  bbox: [0, 0, 55, 8]
  trans:  no

alpha: 1.0
beta: 0.0
