---
i_surf:
  num_rows: 64
  num_cols: 64
  addressing: "strided"
  bbox: [0, 0, 56, 9]

r_div_m:
  num_rows: 64
  num_cols: 32
  addressing: "none"
  bbox: [0, 0, 56, 21]

f_mr_t:
  num_rows: 32
  num_cols: 64
  addressing: "none"
  bbox: [0, 0, 21, 56]

d_k:
  num_rows: 64
  num_cols: 9
  addressing: "strided"
  bbox: [0, 0, 56, 9]

a_plus:
  num_rows: 9
  num_cols: 9
  addressing: "strided"
  bbox: [0, 0, 9, 9]

