# SPDX-FileCopyrightText: 2025 SeisSol Group
#
# SPDX-License-Identifier: MIT
# SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
#
# SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

name: tensorforge
on:
  - push

jobs:
  tensorforge-install:
    name: tensorforge-install
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
