name: TensorForge CI

on: push

jobs:
  general:
    runs-on: ubuntu-24.04
    container: seissol/tensorforge-ci:cicd_develop
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:

    - name: checkout-tensorforge
      uses: actions/checkout@v4

        
    - name: Interface Tests
      run: |
        cd ./tests/interface
        for build_type in Debug Release; do
          mkdir -p ./build-${build_type} && cd ./build-${build_type}
          cmake .. -DCMAKE_BUILD_TYPE=${build_type}
          make
          make test
          cd ..
        done

  codegen:
    runs-on: ubuntu-24.04
    container: seissol/tensorforge-ci:cicd_develop
    timeout-minutes: 10
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    strategy:
      fail-fast: false
      matrix:
        generator: [Eigen, LIBXSMM, LIBXSMM_JIT]
        
    steps:

    - name: checkout-tensorforge
      uses: actions/checkout@v4

    - name: Codegen Tests
      run: |
        cd ./tests/code-gen
        for example in matmul minimal; do
          for build_type in Debug Release; do
            for precision in single double; do
              for arch in snb hsw wsm sm_86; do
                echo " ====== Test Config: ======"
                echo " Build: ${build_type}"
                echo " Architecture: ${arch}"
                echo " Precision: ${precision}"
                echo " Example: ${example}"
                echo "==========================="
                mkdir -p ./build-${example}-${build_type}-${precision}
                cd ./build-${example}-${build_type}-${precision}
                cmake .. -DEXAMPLES=${example} -DCMAKE_BUILD_TYPE=${build_type} -DPRECISION=${precision} -DVARIANT=${{ matrix.generator }} -DARCH=${arch}
                make
                make test
                cd ..
                done
            done
          done
        done
